swagger: "2.0"
info:
  version: 1.0.0
  title: AppGrid API
  description: This document describes the AppGrid RESTful API, a powerful and lightweight read-only API which feeds applications with configuration- and content parameters configured from the AppGrid Admin UI.
schemes:
  - https
host: appgrid-staging-api.cloud.accedo.tv
consumes:
  - application/json
produces:
  - application/json
paths:
   "/session":
    get:
      summary: Create a session
      description: |
                    This method is a starting point for any communication with AppGrid APIs and is used to generate a
                    session key. A session could be created either by passing parameters via query string or headers. If the
                    header approach is chosen, both X-Application-Key and X-User-Id HTTP headers must be provided.

                    <b>Note:</b> AppGrid does not support mixing of header and query string parameters for this method.
                    Application should keep track of the session expiration time and either re-create the session when it’s
                    about to expire, or handle session response about invalid/expired session.
      operationId: create-session-api
      parameters:
        - name: appKey
          in: query
          default: 53fb8fcbe4b077cb2acaa3a6
          description: Application key
          required: true
          type: string
        - name: uuid
          in: query
          default: some-test-value-here
          description: Unique user identifier
          required: true
          type: string
      responses:
        200:
          description: Session key received.
          schema:
            type: array
            items:
              $ref: '#/definitions/getSession'
        404:
          description: Invalid input
definitions:
  getSession:
    allOf:
      - required:
        - appKey
        - uuid
        properties:
          appKey:
            type: string
          uuid:
            type: string